version: '3'
services:
  db:
    image: mysql:8.0.20
    container_name: mysql_container_cardtoon
    restart: always
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: 'petcommunity'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /var/lib/docker/volumes/dockerdata/_data
  front:
    build:
      context: ./client
    ports:
      - 3001:3001
  server:
    build:
      context: ./server
    ports:
      - 3065:3065
    depends_on:
      - db
